import './styles/index.scss';
import type { Metadata } from 'next';
import { Ysabeau } from 'next/font/google';
import StoreProvider from '@/app/StoreProvider';
import { Header } from '@/widgets/header/Header';
import { Footer } from '@/widgets/footer/Footer';
import { HeaderLinks } from '@/widgets/header/headerLinks/HeaderLinks';
import { MenuItems } from '@/widgets/menu/menuItems/MenuItems';

const ysabeau = Ysabeau({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600'],
  variable: '--font-ysabeau',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru' className={ysabeau.variable}>
      <body>
        <StoreProvider>
          <Header>
            <HeaderLinks />
            <MenuItems />
          </Header>
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
